services:
  db:
    image: mariadb:12.0.2
    container_name: time-manager-db
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=time_manager
      - MARIADB_USER=app_user
      - MARIADB_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    image: time-manager-backend:local
    container_name: time-manager-backend
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=time_manager
    depends_on:
      - db
    expose:
      - "3000"

  frontend:
    build: ./frontend
    image: time-manager-frontend:local
    container_name: time-manager-frontend
    expose:
      - "5173"

  nginx:
    image: nginx:stable-alpine
    container_name: time-manager-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  db_data:
